### ISSUE TITLE
Visualizer crashes when using JS file webpacked from the master directory

### ISSUE THREAD

**Issue by CordyChen** [Kitware/visualizer#17]
Visualizer crashes when using JS file webpacked from the master directory, but it works well when using the given file Visualizer.js. I didn't make any change in the directory but just webpacked a new one to test the output file of webpack.
The window on the server is crashing like this:
![default](https://cloud.githubusercontent.com/assets/22293410/23891892/5ddbfe30-08d3-11e7-908f-4a4e2316d8a9.png)
And even the file size is different between the webpacked one and the given one (webpack output file is larger)

**Comment by jourdain** [comment]
Which version of ParaView are you using 5.2, 5.3, master?

How did you build the visualizer bundle?

`npm run build` or `npm run build:release`

**Comment by CordyChen** [comment]
Well I use ParaView 5.2 and I built the bundle by `npm run build:release`.
And oddly I didn't find any error log about it...

**Comment by jourdain** [comment]
Yes, that is weird you that you are not getting roughly the same file size...

I mean, Visualizer/master is not going to work with PV-5.2 because of [that](https://github.com/Kitware/visualizer/issues/15)

Since you are on Windows, I wondering if we have some invalid rules for webpack which could lead to that. Specially related to the path separator.

**Comment by CordyChen** [comment]
Uhha, I download the latest version of ParaView and deploy it again, and use `npm run build`
Now it works well... Maybe it is because of some reasons about Windows platform...
Anyway, thanks a lot!

**Comment by jourdain** [comment]
Glad you got it working, not sure what was the issue. ;-)
